# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: mongodb-v1
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: mongodb
#         version: v1
#     spec:
#       containers:
#       - name: mongodb
#         image: istio/examples-bookinfo-mongodb:1.5.0
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 27017
