apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dev-bookinfo-istio-exekube-us-cert
  namespace: istio-system
spec:
  secretName: istio-ingress-certs
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-stg
  # commonName: example.com
  dnsNames:
  - dev.bookinfo.istio.exekube.us
  - dev.app.istio.exekube.us
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - dev.bookinfo.istio.exekube.us
      - dev.app.istio.exekube.us
