apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stg
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: acme@example.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    http01: {}
# ---
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt
# spec:
#   acme:
#     server: https://acme-v01.api.letsencrypt.org/directory
#     email: acme@example.com
#     privateKeySecretRef:
#       name: letsencrypt-private-key
#     http01: {}
