# Default values for nginx-react.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
resources: {}

image:
  repository: ilyasotkov/forms-app
  tag: latest
  pullPolicy: IfNotPresent

serviceType: ClusterIP
servicePort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: istio

  istio:
    redirectToHttps:
      enabled: true
      service: http-redirector-nginx
      port: 80

  hosts:
    - ${domain_name}
  tls:
    - secretName: istio-ingress-certs
      hosts:
        - ${domain_name}
