# Default values for nginx-react.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
resources: {}

image:
  repository: ilyasotkov/forms-app
  tag: 0.3.2
  pullPolicy: IfNotPresent

serviceType: ClusterIP
servicePort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: istio
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.global-static-ip-name: global-static-ip
  hosts:
    - ${domain_name}
  tls:
    - secretName: istio-ingress-certs
      hosts:
        - ${domain_name}
